//
//  Quotes.swift
//  BookApp
//
//  Created by Caio on 24/10/25.
//

    let quotes = [
        "“It is only with the heart that one can see rightly” - The Little Prince",
        "“The moment you doubt whether you can fly, you cease forever to be able to do it” - Peter Pan",
        "“Tomorrow is always fresh, with no mistakes in it yet” - Anne of Green Gables",
        "“There is some good in this world, and it’s worth fighting for” - The Lord of the Rings",
        "“So we beat on, boats against the current” - The Great Gatsby",
        "“It is not in the stars to hold our destiny but in ourselves” - Julius Caesar",
        "“Happiness can be found even in the darkest of times” - Harry Potter",
        "“All we have to decide is what to do with the time that is given us” - The Lord of the Rings",
        "“The world was hers for the reading” - A Tree Grows in Brooklyn",
        "“You have brains in your head. You have feet in your shoes” - Oh, the Places You’ll Go!",
        "“Even the darkest night will end and the sun will rise” - Les Misérables",
        "“There is no friend as loyal as a book” - Ernest Hemingway",
        "“The only way out of the labyrinth of suffering is to forgive” - Looking for Alaska",
        "“Not all those who wander are lost” - The Lord of the Rings",
        "“It matters not what someone is born, but what they grow to be” - Harry Potter",
        "“The sun himself is weak when he first rises” - Great Expectations",
        "“Isn’t it nice to think that tomorrow is a new day with no mistakes in it yet?” - Anne of Green Gables",
        "“Whatever our souls are made of, his and mine are the same” - Wuthering Heights",
        "“We are such stuff as dreams are made on” - The Tempest",
        "“Until I feared I would lose it, I never loved to read” - To Kill a Mockingbird",
        "“It is our choices that show what we truly are” - Harry Potter",
        "“Books are a uniquely portable magic” - Stephen King",
        "“There is no greater agony than bearing an untold story inside you” - I Know Why the Caged Bird Sings",
        "“All human wisdom is contained in these two words – wait and hope” - The Count of Monte Cristo",
        "“Life appears to me too short to be spent in nursing animosity” - Jane Eyre",
        "“The world breaks everyone, and afterward, many are strong at the broken places” - A Farewell to Arms",
        "“All grown-ups were once children” - The Little Prince",
        "“To love another person is to see the face of God” - Les Misérables",
        "“The answer is not in the stars but in ourselves” - Julius Caesar",
        "“Sometimes the questions are complicated and the answers are simple” - Dr. Seuss",
        "“The earth laughs in flowers” - Ralph Waldo Emerson",
        "“You never really understand a person until you climb into his skin and walk around in it” - To Kill a Mockingbird",
        "“Every human life is worth the same, and worth saving” - Harry Potter",
        "“You can’t get a cup of tea big enough or a book long enough to suit me” - C.S. Lewis",
        "“To define is to limit” - The Picture of Dorian Gray",
        "“A reader lives a thousand lives before he dies” - A Song of Ice and Fire",
        "“The past is never dead. It’s not even past” - William Faulkner",
        "“The mind is its own place, and in itself can make a heaven of hell” - Paradise Lost",
        "“Let us read, and let us dance; these two amusements will never do any harm to the world” - Voltaire",
        "“Real courage is when you know you’re licked before you begin, but you begin anyway” - To Kill a Mockingbird",
        "“It’s the possibility of having a dream come true that makes life interesting” - The Alchemist",
        "“There is nothing like staying at home for real comfort” - Emma",
        "“The world is full of obvious things which nobody by any chance ever observes” - Sherlock Holmes",
        "“A mind needs books as a sword needs a whetstone” - Game of Thrones",
        "“We are all fools in love” - Pride and Prejudice",
        "“The future belongs to those who believe in the beauty of their dreams” - Anne of Green Gables",
        "“The secret of getting ahead is getting started” - Mark Twain",
        "“It was books that made me feel that perhaps I was not completely alone” - Clockwork Angel",
        "“You don’t have to live forever, you just have to live” - Tuck Everlasting",
        "“And now that you don’t have to be perfect, you can be good” - East of Eden",
        "“We read to know we are not alone” - Shadowlands",
        "“To live will be an awfully big adventure” - Peter Pan",
        "“The world is indeed full of peril, and in it there are many dark places; but still there is much that is fair” - The Lord of the Rings",
        "“It does not do to dwell on dreams and forget to live” - Harry Potter",
        "“Courage is found in unlikely places” - The Fellowship of the Ring",
        "“We dream in our waking moments, and walk in our sleep” - The Scarlet Letter",
        "“Time, which changes people, does not alter the image we have retained of them” - Marcel Proust",
        "“There is no charm equal to tenderness of heart” - Emma",
        "“You have been my friend. That in itself is a tremendous thing” - Charlotte’s Web",
        "“All we have to decide is what to do with the time given us” - The Two Towers",
        "“Open your eyes and see what you can with them before they close forever” - All the Light We Cannot See",
        "“Whatever our souls are made of, his and mine are the same” - Wuthering Heights",
        "“Beware; for I am fearless, and therefore powerful” - Frankenstein",
        "“The world is full of things worth fighting for” - The Hobbit",
        "“The sun shines not on us but in us” - John Muir",
        "“It is never too late to be what you might have been” - Middlemarch",
        "“People generally see what they look for” - To Kill a Mockingbird",
        "“The light shines in the darkness, and the darkness has not overcome it” - The Bible",
        "“There is a crack in everything, that’s how the light gets in” - Leonard Cohen (Beautiful Losers)",
        "“We are all in the gutter, but some of us are looking at the stars” - Lady Windermere’s Fan",
        "“Not all those who wander are lost” - The Fellowship of the Ring",
        "“You can’t stay in your corner of the forest waiting for others to come to you” - Winnie the Pooh",
        "“The world was quiet here” - A Series of Unfortunate Events",
        "“Words are, in my not-so-humble opinion, our most inexhaustible source of magic” - Harry Potter",
        "“It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends” - Harry Potter",
        "“Even miracles take a little time” - Cinderella",
        "“To be fond of dancing was a certain step towards falling in love” - Pride and Prejudice",
        "“Hope is the thing with feathers that perches in the soul” - Emily Dickinson",
        "“Some infinities are bigger than other infinities” - The Fault in Our Stars",
        "“Everything was beautiful and nothing hurt” - Slaughterhouse-Five",
        "“The only limits for tomorrow are the doubts we have today” - The Old Man and the Sea",
        "“It is only with gratitude that life becomes rich” - The Brothers Karamazov",
        "“The best way to find out if you can trust somebody is to trust them” - The Sun Also Rises",
        "“There is nothing either good or bad, but thinking makes it so” - Hamlet",
        "“We are what we believe we are” - Don Quixote",
        "“Do I dare disturb the universe?” - The Love Song of J. Alfred Prufrock",
        "“The goal of life is living in agreement with nature” - Zeno of Citium (Meditations)",
        "“The past is a ghost, the future a dream, and all we ever have is now” - The Name of the Wind",
        "“Everything you can imagine is real” - The Picture of Dorian Gray",
        "“Until I feared I would lose it, I never loved to read” - To Kill a Mockingbird",
        "“A man is but the product of his thoughts; what he thinks, he becomes” - Gandhi (Young India)",
        "“After all, tomorrow is another day” - Gone with the Wind",
        "“Nothing is impossible, the word itself says ‘I’m possible!’” - Breakfast at Tiffany’s",
        "“We are all stories in the end. Just make it a good one” - Doctor Who: The Novel Adventures",
        "“Everything has beauty, but not everyone sees it” - The Analects",
        "“There are far, far better things ahead than any we leave behind” - The Last Battle",
        "“Without rain, there would be no rainbow” - The Wizard of Oz",
        "“One day I will find the right words, and they will be simple” - Big Sur",
        "“Home is the nicest word there is” - Little House on the Prairie",
        "“Light thinks it travels faster than anything, but it is wrong” - Good Omens",
        "“The more that you read, the more things you will know” - Dr. Seuss",
        "“A single dream is more powerful than a thousand realities” - The Lord of the Rings",
        "“The beginning is always today” - Mary Shelley",
        "“Nothing ever ends poetically. It ends and we turn it into poetry” - The Sun and Her Flowers",
        "“All endings are also beginnings. We just don’t know it at the time” - The Five People You Meet in Heaven",
        "“Hope smiles from the threshold of the year to come” - Alfred Lord Tennyson",
        "“It is only when we forget all our learning that we begin to know” - Walden",
        "“Some books leave us free and some books make us free” - Ralph Waldo Emerson",
        "“The world is before you, and you need not take it or leave it as it was when you came in” - James Baldwin",
        "“The magic is always in the details” - The God of Small Things",
        "“How wonderful it is that nobody need wait a single moment before starting to improve the world” - The Diary of Anne Frank",
        "“Nothing behind me, everything ahead of me, as is ever so on the road” - On the Road",
        "“Life is either a daring adventure or nothing at all” - The Open Door",
        "“There is a kind of magicness about going far away and then coming back all changed” - The Secret Garden",
        "“One child, one teacher, one book, one pen can change the world” - I Am Malala",
        "“The future belongs to those who believe in the beauty of their dreams” - Anne of Green Gables",
        "“Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us dragons can be beaten” - Coraline",
        "“It is not true that people stop pursuing dreams because they grow old, they grow old because they stop pursuing dreams” - The Alchemist",
        "“To love another person is to see the face of God” - Les Misérables",
        "“Everything you’ve ever wanted is on the other side of fear” - The Old Man and the Sea",
        "“The secret of life, though, is to fall seven times and to get up eight” - The Alchemist",
        "“The soul becomes dyed with the color of its thoughts” - Meditations",
        "“You are never too old to set another goal or to dream a new dream” - The Chronicles of Narnia",
        "“Books are mirrors: you only see in them what you already have inside you” - The Shadow of the Wind",
        "“The simple things are also the most extraordinary things” - The Alchemist",
        "“The universe is made of stories, not of atoms” - The Golden Notebook",
        "“Life changes fast. Life changes in the instant” - The Year of Magical Thinking",
        "“There is nothing more necessary than hope” - A Tale of Two Cities",
        "“Not all those who wander are lost” - The Lord of the Rings",
        "“To learn who rules over you, simply find out who you are not allowed to criticize” - Voltaire",
        "“It was the best of times, it was the worst of times” - A Tale of Two Cities",
        "“I am rooted, but I flow” - The Waves",
        "“We are all broken, that’s how the light gets in” - Beautiful Losers",
        "“The world gives you so much pain and here you are making gold out of it” - The Sun and Her Flowers",
        "“One cannot be always laughing at a man without now and then stumbling on something witty” - Pride and Prejudice",
        "“We need never be ashamed of our tears” - Great Expectations",
        "“You can’t live your life for other people” - The Notebook",
        "“Stories are wild creatures, the monster said” - A Monster Calls",
        "“It was always about hope” - The Book Thief",
        "“Every human heart is a story waiting to be read” - The Night Circus",
        "“We are all travelers in the wilderness of this world” - Vanity Fair",
        "“It matters not how strait the gate, how charged with punishments the scroll” - Invictus",
        "“There are no faster or firmer friendships than those formed between people who love the same books” - The Turn of the Screw",
        "“It’s never too late to be kind” - Anne of Green Gables",
        "“Be not afraid of greatness” - Twelfth Night",
        "“You forget what you want to remember, and you remember what you want to forget” - The Road",
        "“Without stories, we would go mad” - The Ocean at the End of the Lane",
        "“Sometimes you have to travel far to find what is near” - The Wizard of Earthsea",
        "“There is no enjoyment like reading” - Pride and Prejudice",
        "“The wind was a torrent of darkness among the gusty trees” - The Highwayman",
        "“You can’t get away from yourself by moving from one place to another” - The Sun Also Rises",
        "“Words are life, and reading them is living twice” - The Book Thief",
        "“Read in order to live” - Gustave Flaubert",
        "“You must write your first draft with your heart” - On Writing",
        "“The world was hers for the reading” - A Tree Grows in Brooklyn",
        "“The moment you open a book, you step into another world” - Inkheart",
        "“To learn to read is to light a fire” - Victor Hugo",
        "“There is no friend as loyal as a book” - Ernest Hemingway",
        "“Books are the quietest and most constant of friends” - Charles W. Eliot",
        "“Reading is essential for those who seek to rise above the ordinary” - Jim Rohn",
        "“The person who deserves most pity is a lonesome one on a rainy day who doesn’t know how to read” - Benjamin Franklin",
        "“The library is inhabited by spirits that come out of the pages at night” - Isabel Allende",
        "“A room without books is like a body without a soul” - Marcus Tullius Cicero",
        "“The reading of all good books is like conversation with the finest minds of past centuries” - Descartes",
        "“That’s the thing about books. They let you travel without moving your feet” - The Namesake",
        "“Each book was a world unto itself” - Fahrenheit 451",
        "“The books transported her into new worlds” - Matilda",
        "“Reading gives us someplace to go when we have to stay where we are” - Mason Cooley",
        "“There is more treasure in books than in all the pirate’s loot on Treasure Island” - Walt Disney",
        "“I have always imagined that paradise will be a kind of library” - Jorge Luis Borges",
        "“The man who does not read has no advantage over the man who cannot read” - Mark Twain",
        "“A book is a dream that you hold in your hands” - Neil Gaiman",
        "“Reading is departure and arrival” - Terri Guillemets",
        "“Once you learn to read, you will be forever free” - Frederick Douglass",
        "“Books are a uniquely portable magic” - Stephen King",
        "“The story is always better when you read it yourself” - The Book Thief",
        "“Reading one book is like eating one potato chip” - Diane Duane",
        "“The love of learning, the sequestered nooks, and all the sweet serenity of books” - Henry Wadsworth Longfellow",
        "“A great book should leave you with many experiences” - William Styron",
        "“Some stories stay with us forever” - The Hobbit",
        "“Reading brings us unknown friends” - Honoré de Balzac",
        "“A book is proof that humans can work magic” - Carl Sagan",
        "“Literature is the most agreeable way of ignoring life” - Fernando Pessoa",
        "“The world belongs to those who read” - Rick Holland",
        "“The dearest ones of time, the strongest friends of the soul—books” - Emily Dickinson",
        "“I cannot live without books” - Thomas Jefferson",
        "“There are worse crimes than burning books. One of them is not reading them” - Ray Bradbury",
        "“Books are lighthouses erected in the great sea of time” - E.P. Whipple",
        "“No entertainment is so cheap as reading” - Mary Wortley Montagu",
        "“A book is a gift you can open again and again” - Garrison Keillor",
        "“Reading furnishes the mind only with materials of knowledge” - John Locke",
        "“The more that you read, the more things you will know” - Dr. Seuss",
        "“A word after a word after a word is power” - Margaret Atwood",
        "“A book must be the axe for the frozen sea within us” - Franz Kafka",
        "“There are perhaps no days of our childhood we lived so fully as those we spent with a favorite book” - Marcel Proust",
        "“Reading is an exercise in empathy” - Malorie Blackman",
        "“Books train your imagination to think big” - Taylor Swift (Little Golden Book)",
        "“The man who reads nothing at all is better educated than the man who reads nothing but newspapers” - Thomas Jefferson",
        "“Reading is dreaming with open eyes” - Yoyo Tan",
        "“Books are the mirrors of the soul” - Virginia Woolf",
        "“The joy of reading is in discovering worlds you never knew existed” - Paulo Coelho",
        "“Between the pages of a book is a lovely place to be” - Unknown"
        ]

let frases = [
  "“Só se vê bem com o coração” - O Pequeno Príncipe",
  "“No momento em que duvida se pode voar, deixa de poder fazê-lo para sempre” - Peter Pan",
  "“O amanhã é sempre novo, ainda sem erros” - Anne de Green Gables",
  "“Há algo de bom neste mundo, e vale a pena lutar por isso” - O Senhor dos Anéis",
  "“E assim seguimos, barcos contra a correnteza” - O Grande Gatsby",
  "“Não está nas estrelas o nosso destino, mas em nós mesmos” - Júlio César",
  "“A felicidade pode ser encontrada até nos tempos mais sombrios” - Harry Potter",
  "“Tudo o que temos de decidir é o que fazer com o tempo que nos é dado” - O Senhor dos Anéis",
  "“O mundo era dela para ser lido” - Uma Árvore Cresce no Brooklyn",
  "“Você tem cérebro na cabeça. Você tem pés nos sapatos” - Ah, os Lugares aonde Você Irá!",
  "“Mesmo a noite mais escura terminará e o sol nascerá” - Os Miseráveis",
  "“Não há amigo tão leal quanto um livro” - Ernest Hemingway",
  "“A única saída do labirinto do sofrimento é o perdão” - Quem é Você, Alasca?",
  "“Nem todos os que vagueiam estão perdidos” - O Senhor dos Anéis",
  "“O que importa não é o que alguém nasce sendo, mas o que se torna” - Harry Potter",
  "“O próprio sol é fraco quando nasce” - Grandes Esperanças",
  "“Não é bom pensar que amanhã é um novo dia sem erros ainda?” - Anne de Green Gables",
  "“Seja qual for a matéria de nossas almas, as dele e as minhas são iguais” - O Morro dos Ventos Uivantes",
  "“Somos feitos da mesma matéria dos sonhos” - A Tempestade",
  "“Até temer perdê-la, nunca amei a leitura” - O Sol é para Todos",
  "“São nossas escolhas que mostram quem realmente somos” - Harry Potter",
  "“Os livros são uma magia portável única” - Stephen King",
  "“Não há agonia maior do que carregar uma história não contada dentro de si” - Eu Sei Por Que o Pássaro Canta na Gaiola",
  "“Toda sabedoria humana está contida nestas duas palavras – esperar e ter esperança” - O Conde de Monte Cristo",
  "“A vida me parece curta demais para ser gasta nutrindo animosidades” - Jane Eyre",
  "“O mundo quebra a todos, e depois muitos se tornam fortes nos lugares quebrados” - Adeus às Armas",
  "“Todos os adultos já foram crianças” - O Pequeno Príncipe",
  "“Amar outra pessoa é ver o rosto de Deus” - Os Miseráveis",
  "“A resposta não está nas estrelas, mas em nós mesmos” - Júlio César",
  "“Às vezes as perguntas são complicadas e as respostas simples” - Dr. Seuss",
  "“A terra ri em flores” - Ralph Waldo Emerson",
  "“Você nunca entende realmente uma pessoa até subir em sua pele e andar nela” - O Sol é para Todos",
  "“Toda vida humana vale o mesmo, e vale ser salva” - Harry Potter",
  "“Não há chá grande o bastante nem livro longo o suficiente para mim” - C.S. Lewis",
  "“Definir é limitar” - O Retrato de Dorian Gray",
  "“Um leitor vive mil vidas antes de morrer” - As Crônicas de Gelo e Fogo",
  "“O passado nunca morre. Nem mesmo é passado” - William Faulkner",
  "“A mente é seu próprio lugar, e nela pode fazer do inferno um paraíso” - Paraíso Perdido",
  "“Leamos e dancemos; esses dois divertimentos jamais farão mal ao mundo” - Voltaire",
  "“Coragem verdadeira é começar mesmo sabendo que já perdeu” - O Sol é para Todos",
  "“É a possibilidade de um sonho se realizar que torna a vida interessante” - O Alquimista",
  "“Não há nada como estar em casa para verdadeiro conforto” - Emma",
  "“O mundo está cheio de coisas óbvias que ninguém jamais observa” - Sherlock Holmes",
  "“A mente precisa de livros como uma espada precisa de pedra de amolar” - Game of Thrones",
  "“Somos todos tolos no amor” - Orgulho e Preconceito",
  "“O futuro pertence àqueles que acreditam na beleza de seus sonhos” - Anne de Green Gables",
  "“O segredo de começar é começar” - Mark Twain",
  "“Foram os livros que me fizeram sentir que talvez eu não estivesse completamente sozinho” - Anjo Mecânico",
  "“Você não precisa viver para sempre, só precisa viver” - Tuck Everlasting",
  "“Agora que você não precisa ser perfeito, pode ser bom” - Leste do Éden",
  "“Lemos para saber que não estamos sozinhos” - Terra das Sombras",
  "“Viver será uma grande aventura” - Peter Pan",
  "“O mundo está cheio de perigos e lugares escuros; mas ainda há muita beleza” - O Senhor dos Anéis",
  "“Não adianta viver sonhando e esquecer de viver” - Harry Potter",
  "“A coragem é encontrada em lugares improváveis” - A Sociedade do Anel",
  "“Sonhamos em nossos momentos acordados e caminhamos dormindo” - A Letra Escarlate",
  "“O tempo muda as pessoas, mas não a imagem que guardamos delas” - Marcel Proust",
  "“Não há encanto igual à ternura do coração” - Emma",
  "“Você foi meu amigo. Isso por si só é uma coisa tremenda” - A Menina e o Porquinho",
  "“Tudo o que temos de decidir é o que fazer com o tempo que nos é dado” - As Duas Torres",
  "“Abra os olhos e veja o que pode antes que se fechem para sempre” - Toda Luz Que Não Podemos Ver",
  "“Seja qual for a matéria de nossas almas, as dele e as minhas são iguais” - O Morro dos Ventos Uivantes",
  "“Cuidado; pois sou destemido, e portanto poderoso” - Frankenstein",
  "“O mundo está cheio de coisas pelas quais vale a pena lutar” - O Hobbit",
  "“O sol não brilha sobre nós, mas dentro de nós” - John Muir",
  "“Nunca é tarde demais para ser o que você poderia ter sido” - Middlemarch",
  "“As pessoas geralmente veem o que procuram” - O Sol é para Todos",
  "“A luz brilha nas trevas, e as trevas não a venceram” - A Bíblia",
  "“Há uma fenda em tudo, é assim que a luz entra” - Leonard Cohen",
  "“Estamos todos no esgoto, mas alguns de nós olham para as estrelas” - Leque de Lady Windermere",
  "“Nem todos os que vagueiam estão perdidos” - A Sociedade do Anel",
  "“Você não pode ficar no seu canto da floresta esperando que os outros venham até você” - Ursinho Pooh",
  "“O mundo estava quieto aqui” - Desventuras em Série",
  "“As palavras são, em minha nada humilde opinião, nossa fonte mais inesgotável de magia” - Harry Potter",
  "“É preciso tanta coragem para enfrentar os amigos quanto os inimigos” - Harry Potter",
  "“Mesmo milagres levam um pouco de tempo” - Cinderela",
  "“Gostar de dançar era um certo passo para se apaixonar” - Orgulho e Preconceito",
  "“A esperança é a coisa com penas que pousa na alma” - Emily Dickinson",
  "“Alguns infinitos são maiores que outros infinitos” - A Culpa é das Estrelas",
  "“Tudo era bonito e nada doía” - Matadouro Cinco",
  "“Os únicos limites para o amanhã são as dúvidas que temos hoje” - O Velho e o Mar",
  "“É só com gratidão que a vida se torna rica” - Os Irmãos Karamázov",
  "“A melhor forma de saber se pode confiar em alguém é confiando” - O Sol Também se Levanta",
  "“Não há nada bom ou mau, mas o pensamento o faz assim” - Hamlet",
  "“Somos o que acreditamos ser” - Dom Quixote",
  "“Ouso perturbar o universo?” - O Amor Canta em J. Alfred Prufrock",
  "“O objetivo da vida é viver em harmonia com a natureza” - Meditações",
  "“O passado é um fantasma, o futuro um sonho, e tudo o que temos é o agora” - O Nome do Vento",
  "“Tudo o que você pode imaginar é real” - O Retrato de Dorian Gray",
  "“Até temer perdê-la, nunca amei a leitura” - O Sol é para Todos",
  "“O homem é produto de seus pensamentos; o que pensa, ele se torna” - Gandhi",
  "“Afinal, amanhã é outro dia” - E o Vento Levou",
  "“Nada é impossível, a própria palavra diz ‘sou possível!’” - Bonequinha de Luxo",
  "“Somos todos histórias no fim. Apenas faça dela uma boa” - Doctor Who: As Aventuras em Livro",
  "“Tudo tem beleza, mas nem todos a veem” - Os Analectos",
  "“Há coisas muito melhores à frente do que qualquer uma que deixamos para trás” - A Última Batalha",
  "“Sem chuva, não haveria arco-íris” - O Mágico de Oz",
  "“Um dia encontrarei as palavras certas, e elas serão simples” - Big Sur",
  "“Lar é a palavra mais bonita que existe” - A Casa da Pequena Planície",
  "“A luz pensa que viaja mais rápido que qualquer coisa, mas está errada” - Belas Maldições",
  "“Quanto mais você lê, mais coisas saberá” - Dr. Seuss",
  "“Um único sonho é mais poderoso que mil realidades” - O Senhor dos Anéis",
    "“O começo é sempre hoje” - Mary Shelley",
    "“Nada termina poeticamente. Termina e nós transformamos em poesia” - O Sol e Suas Flores",
    "“Todo fim é também um começo. Só não sabemos disso na hora” - As Cinco Pessoas que Você Encontra no Céu",
    "“A esperança sorri no limiar do ano que está por vir” - Alfred Lord Tennyson",
    "“Só quando esquecemos tudo o que aprendemos é que começamos a saber” - Walden",
    "“Alguns livros nos deixam livres e outros nos fazem livres” - Ralph Waldo Emerson",
    "“O mundo está diante de você, e não precisa aceitá-lo como era quando chegou” - James Baldwin",
    "“A magia está sempre nos detalhes” - O Deus das Pequenas Coisas",
    "“Como é maravilhoso que ninguém precise esperar um momento sequer para começar a melhorar o mundo” - O Diário de Anne Frank",
    "“Nada atrás de mim, tudo à frente, como sempre na estrada” - On the Road",
    "“A vida é ou uma aventura ousada ou nada” - A Porta Aberta",
    "“Há uma espécie de magia em ir para longe e depois voltar mudado” - O Jardim Secreto",
    "“Uma criança, um professor, um livro e uma caneta podem mudar o mundo” - Eu Sou Malala",
    "“O futuro pertence àqueles que acreditam na beleza de seus sonhos” - Anne de Green Gables",
    "“Os contos de fadas são mais que verdadeiros: não porque dizem que dragões existem, mas porque dizem que eles podem ser derrotados” - Coraline",
    "“Não é verdade que as pessoas param de sonhar porque envelhecem; elas envelhecem porque param de sonhar” - O Alquimista",
    "“Amar outra pessoa é ver o rosto de Deus” - Os Miseráveis",
    "“Tudo o que você sempre quis está do outro lado do medo” - O Velho e o Mar",
    "“O segredo da vida é cair sete vezes e levantar-se oito” - O Alquimista",
    "“A alma se tinge com a cor de seus pensamentos” - Meditações",
    "“Você nunca é velho demais para sonhar um novo sonho” - As Crônicas de Nárnia",
    "“Os livros são espelhos: você só vê neles o que já tem dentro de si” - A Sombra do Vento",
    "“As coisas simples são também as mais extraordinárias” - O Alquimista",
    "“O universo é feito de histórias, não de átomos” - O Caderno Dourado",
    "“A vida muda rápido. A vida muda num instante” - O Ano do Pensamento Mágico",
    "“Não há nada mais necessário do que a esperança” - Um Conto de Duas Cidades",
    "“Nem todos os que vagam estão perdidos” - O Senhor dos Anéis",
    "“Para saber quem manda sobre você, descubra quem você não pode criticar” - Voltaire",
    "“Foi o melhor dos tempos, foi o pior dos tempos” - Um Conto de Duas Cidades",
    "“Sou enraizada, mas fluo” - As Ondas",
    "“Todos somos quebrados, é assim que a luz entra” - Os Belos Vencidos",
    "“O mundo lhe dá tanta dor, e ainda assim você transforma isso em ouro” - O Sol e Suas Flores",
    "“Não se pode rir de um homem o tempo todo sem tropeçar em algo espirituoso” - Orgulho e Preconceito",
    "“Nunca devemos nos envergonhar de nossas lágrimas” - Grandes Esperanças",
    "“Você não pode viver sua vida pelos outros” - Diário de uma Paixão",
    "“Histórias são criaturas selvagens, disse o monstro” - Sete Minutos Depois da Meia-Noite",
    "“Sempre foi sobre esperança” - A Menina que Roubava Livros",
    "“Todo coração humano é uma história esperando para ser lida” - O Circo da Noite",
    "“Somos todos viajantes no deserto deste mundo” - Vaidade Justa",
    "“Pouco importa quão estreito o portão, quão carregado de punições o rolo” - Invictus",
    "“Não há amizades mais fortes do que as entre pessoas que amam os mesmos livros” - A Volta do Parafuso",
    "“Nunca é tarde demais para ser gentil” - Anne de Green Gables",
    "“Não temas a grandeza” - Noite de Reis",
    "“Você esquece o que quer lembrar e lembra o que quer esquecer” - A Estrada",
    "“Sem histórias, enlouqueceríamos” - O Oceano no Fim do Caminho",
    "“Às vezes é preciso viajar longe para encontrar o que está perto” - O Feiticeiro de Terramar",
    "“Não há prazer igual ao da leitura” - Orgulho e Preconceito",
    "“O vento era um turbilhão de escuridão entre as árvores tempestuosas” - O Salteador",
    "“Você não pode fugir de si mesmo mudando de lugar” - O Sol Também se Levanta",
    "“Palavras são vida, e lê-las é viver duas vezes” - A Menina que Roubava Livros",
    "“Leia para viver” - Gustave Flaubert",
    "“Você deve escrever seu primeiro rascunho com o coração” - Sobre a Escrita",
    "“O mundo era dela para ser lido” - Uma Árvore Cresce no Brooklyn",
    "“No momento em que abre um livro, entra em outro mundo” - Coração de Tinta",
    "“Aprender a ler é acender um fogo” - Victor Hugo",
    "“Não há amigo tão leal quanto um livro” - Ernest Hemingway",
    "“Os livros são os amigos mais silenciosos e constantes” - Charles W. Eliot",
    "“Ler é essencial para quem busca ir além do comum” - Jim Rohn",
    "“A pessoa mais digna de pena é a solitária num dia chuvoso que não sabe ler” - Benjamin Franklin",
    "“A biblioteca é habitada por espíritos que saem das páginas à noite” - Isabel Allende",
    "“Um quarto sem livros é como um corpo sem alma” - Marco Túlio Cícero",
    "“Ler bons livros é como conversar com as melhores mentes dos séculos passados” - Descartes",
    "“Essa é a beleza dos livros: permitem viajar sem mover os pés” - O Namesake",
    "“Cada livro era um mundo em si mesmo” - Fahrenheit 451",
    "“Os livros a transportavam para novos mundos” - Matilda",
    "“Ler nos dá um lugar para ir quando precisamos ficar onde estamos” - Mason Cooley",
    "“Há mais tesouros nos livros do que em todo o saque dos piratas” - A Ilha do Tesouro",
    "“Sempre imaginei que o paraíso fosse uma espécie de biblioteca” - Jorge Luis Borges",
    "“O homem que não lê não tem vantagem sobre o que não sabe ler” - Mark Twain",
    "“Um livro é um sonho que você segura nas mãos” - Neil Gaiman",
    "“Ler é partida e chegada” - Terri Guillemets",
    "“Depois que você aprende a ler, será livre para sempre” - Frederick Douglass",
    "“Os livros são uma magia portável única” - Stephen King",
    "“A história é sempre melhor quando você mesmo a lê” - A Menina que Roubava Livros",
    "“Ler um livro é como comer uma batata frita” - Diane Duane",
    "“O amor pelo aprendizado, os recantos tranquilos e toda a doçura serena dos livros” - Henry Wadsworth Longfellow",
    "“Um grande livro deve deixá-lo com muitas experiências” - William Styron",
    "“Algumas histórias ficam conosco para sempre” - O Hobbit",
    "“Ler nos traz amigos desconhecidos” - Honoré de Balzac",
    "“Um livro é a prova de que humanos podem fazer magia” - Carl Sagan",
    "“A literatura é a maneira mais agradável de ignorar a vida” - Fernando Pessoa",
    "“O mundo pertence a quem lê” - Rick Holland",
    "“Os mais queridos do tempo, os amigos mais fortes da alma — os livros” - Emily Dickinson",
    "“Não posso viver sem livros” - Thomas Jefferson",
    "“Há crimes piores do que queimar livros. Um deles é não lê-los” - Ray Bradbury",
    "“Os livros são faróis erguidos no grande mar do tempo” - E.P. Whipple",
    "“Nenhum entretenimento é tão barato quanto a leitura” - Mary Wortley Montagu",
    "“Um livro é um presente que você pode abrir de novo e de novo” - Garrison Keillor",
    "“A leitura fornece à mente apenas os materiais do conhecimento” - John Locke",
    "“Quanto mais você lê, mais coisas saberá” - Dr. Seuss",
    "“Uma palavra após a outra é poder” - Margaret Atwood",
    "“Um livro deve ser o machado para o mar congelado dentro de nós” - Franz Kafka",
    "“Talvez não haja dias da infância que vivamos tão plenamente quanto aqueles passados com um livro favorito” - Marcel Proust",
    "“Ler é um exercício de empatia” - Malorie Blackman",
    "“Os livros treinam sua imaginação para pensar grande” - Taylor Swift (Pequeno Livro Dourado)",
    "“O homem que não lê nada é mais instruído que o que lê apenas jornais” - Thomas Jefferson",
    "“Ler é sonhar de olhos abertos” - Yoyo Tan",
    "“Os livros são os espelhos da alma” - Virginia Woolf",
    "“A alegria da leitura está em descobrir mundos que você nunca soube que existiam” - Paulo Coelho",
    "“Entre as páginas de um livro é um lugar adorável para estar” - Desconhecido",
  "“Viver é muito perigoso, mas é bom demais.” - Grande Sertão: Veredas",
  "“A vida é feita de coragem.” - Grande Sertão: Veredas",
  "“Quem olha para fora sonha, quem olha para dentro desperta.” - O Alquimista",
  "“Quando você quer alguma coisa, todo o universo conspira para que realize seu desejo.” - O Alquimista",
  "“O que vale na vida não é o ponto de partida, e sim a caminhada.” - Caminho Suave",
  "“O segredo é não correr atrás das borboletas, é cuidar do jardim para que elas venham até você.” - Dom Casmurro",
  "“A liberdade é pouco. O que eu desejo ainda não tem nome.” - Perto do Coração Selvagem",
  "“A vida é um sopro.” - Minha Arquitetura",
  "“O tempo é o melhor autor: sempre encontra um final perfeito.” - A Rua dos Cataventos",
  "“A vida é feita de pequenas felicidades.” - O Tempo e o Vento",
  "“A alegria é a prova dos nove.” - Serafim Ponte Grande",
  "“O que é verdadeiro volta de algum jeito.” - A Hora da Estrela",
  "“Ser feliz sem motivo é a mais autêntica forma de felicidade.” - Alguma Poesia",
  "“O sertão é dentro da gente.” - Grande Sertão: Veredas",
  "“A beleza é o brilho de uma alma tranquila.” - Cecília Meireles: Obra Completa",
  "“Há sempre um pouco de loucura no amor.” - Dom Casmurro",
  "“Não se pode possuir o que não se compreende.” - As Meninas",
  "“A vida é curta demais para ser pequena.” - Livro do Desassossego",
  "“Quem caminha sozinho pode até chegar mais rápido, mas aquele que vai acompanhado vai mais longe.” - Felicidade Clandestina",
  "“A simplicidade é o último grau de sofisticação.” - Pensamentos Soltos",
  "“A vida é a arte do encontro, embora haja tanto desencontro pela vida.” - Para Viver um Grande Amor",
  "“Tudo vale a pena se a alma não é pequena.” - Mensagem",
  "“A esperança é o que nos move.” - A Pedra do Reino",
  "“O amor é quando a gente mora um no outro.” - Porta de Vidro",
  "“Quem lê, nunca está sozinho.” - Reinações de Narizinho",
  "“A leitura é o primeiro passo para a liberdade.” - Educação e Mudança",
  "“A vida é um mosaico de instantes.” - O Primo Basílio",
  "“Nada é pequeno quando o amor é grande.” - Romanceiro da Inconfidência",
  "“O coração é terra que ninguém vê.” - Tutaméia",
  "“Há pessoas que choram por saber que as rosas têm espinhos.” - Memórias Póstumas de Brás Cubas",
  "“A saudade é o que faz as coisas pararem no tempo.” - Baú de Espantos",
  "“Tudo o que é bom dura o tempo necessário para ser inesquecível.” - O Encontro Marcado",
  "“A felicidade é uma questão de luz interior.” - O Gato Malhado e a Andorinha Sinhá",
  "“A vida não é o que a gente vive, mas o que a gente recorda.” - Viver para Contar",
  "“A esperança é um bicho teimoso.” - O Auto da Compadecida",
  "“Quem tem luz própria incomoda quem está no escuro.” - A Paixão Segundo G.H.",
  "“Não há nada mais bonito do que ser o que se é.” - A Cidade e as Serras",
  "“As coisas mais simples são as mais extraordinárias.” - O Alquimista",
  "“A felicidade está nas pequenas coisas.” - O Tempo e o Vento",
  "“A coragem é a primeira das virtudes.” - O Cão Sem Plumas",
  "“O amor é eterno enquanto dura.” - Soneto da Fidelidade",
  "“As palavras têm o poder de curar.” - A Menina que Roubava Livros (edição brasileira)",
  "“A vida é feita de começos e recomeços.” - Claraboia",
  "“A leitura é o passaporte para infinitos mundos.” - Reinações de Narizinho",
  "“Quem sonha move o mundo.” - Dois Irmãos",
  "“Nada é mais libertador do que compreender.” - As Meninas",
  "“Ler é tocar o invisível com os olhos.” - O Mistério do Coelho Pensante",
  "“A vida é uma obra de arte que se escreve todos os dias.” - Pequenas Alegrias",
  "“Há sempre um novo amanhã escondido atrás de cada página.” - O Menino do Dedo Verde",
  "“A leitura é um ato de amor.” - Educação e Mudança",
  "“Quem lê floresce.” - Reinações de Narizinho",
  "“A sabedoria mora na calma.” - Grande Sertão: Veredas",
  "“As histórias são pontes que unem as pessoas.” - A Bolsa Amarela",
  "“O livro é uma casa onde a alma descansa.” - O Fantástico Mistério de Feiurinha",
  "“A leitura transforma o silêncio em sabedoria.” - Angélica e o Mundo",
  "“Quem lê se descobre.” - A Casa da Madrinha",
  "“Ler é o início da coragem.” - As Três Marias",
  "“A vida é feita de recomeços e páginas em branco.” - O Encontro Marcado",
  "“A leitura é um abrigo contra a pressa do mundo.” - Flicts",
  "“A imaginação é o primeiro passo para a liberdade.” - Sítio do Picapau Amarelo",
  "“Os sonhos são o combustível da alma.” - O Alquimista",
  "“Ler é respirar por outros pulmões.” - Felicidade Clandestina",
  "“Cada leitura é uma vida a mais.” - Vidas Secas",
  "“Os livros nos ensinam a ver o que os olhos não enxergam.” - O Mundo de Sofia (edição brasileira)",
  "“Quem lê nunca envelhece.” - As Aventuras de Tom Mix no Brasil",
  "“Ler é ouvir o mundo sussurrar segredos.” - O Gato Malhado e a Andorinha Sinhá",
  "“A leitura é o lugar onde a alma se alimenta.” - A Menina e o Pássaro Encantado",
  "“Toda leitura é uma viagem sem retorno.” - O Espelho",
  "“Os livros não têm pressa, esperam a gente amadurecer.” - A Bolsa Amarela",
  "“Cada livro é uma ponte entre o sonho e a realidade.” - Claraboia",
  "“A imaginação é o abrigo do impossível.” - Reinações de Narizinho",
  "“A vida é mais bonita quando a gente lê.” - O Pequeno Príncipe (edição brasileira)",
  "“O melhor da vida é aquilo que não se pode explicar.” - Água Viva",
  "“Os livros são espelhos de quem somos e quem queremos ser.” - A Bolsa Amarela",
  "“Ler é dar sentido ao silêncio.” - Lygia Bojunga: O Sofá Estampado",
  "“A leitura é a alma que passeia livre.” - Cartas a um Jovem Poeta (edição brasileira)",
  "“As páginas de um livro são asas dobradas.” - Flicts",
  "“Quem lê viaja sem sair do sofá.” - Reinações de Narizinho",
  "“A vida é feita de histórias e pausas.” - O Vendedor de Sonhos",
  "“Cada livro traz uma semente de mudança.” - Educação como Prática da Liberdade",
  "“O livro é o melhor abrigo da tempestade.” - Corda Bamba",
  "“Ler é acender uma vela dentro de si.” - Angélica e o Mundo",
  "“As histórias salvam quem as conta e quem as escuta.” - Ponciá Vicêncio",
  "“Quem lê se torna o que imagina.” - O Reizinho Mandão",
  "“A leitura é o espelho da coragem silenciosa.” - O Pássaro Raro",
  "“Um livro aberto é um coração pulsando.” - A Menina e o Pássaro Encantado",
  "“Ler é um jeito de renascer.” - Claraboia",
  "“As palavras certas mudam o rumo do vento.” - Dois Irmãos",
  "“A leitura é uma forma de esperança.” - Educação e Mudança",
  "“Os livros são a prova de que o ser humano acredita em futuro.” - Flicts",
  "“Toda página é um convite para começar de novo.” - O Encontro Marcado",
  "“A leitura é o ato mais íntimo da liberdade.” - Ponciá Vicêncio",
  "“Quem lê encontra abrigo em qualquer lugar.” - A Bolsa Amarela",
  "“O livro é o silêncio que fala.” - O Sofá Estampado",
  "“A leitura é um mergulho em si mesmo.” - Água Viva",
  "“Os livros são o mapa do invisível.” - O Alquimista",
  "“Quem lê sempre chega em casa.” - Angélica e o Mundo"
];

let citazioni = [
  "“Non si vede bene che col cuore” - Il Piccolo Principe",
  "“Nel momento in cui dubiti di poter volare, smetti per sempre di essere in grado di farlo” - Peter Pan",
  "“Domani è sempre un giorno nuovo, senza errori ancora” - Anna dai capelli rossi",
  "“C’è del buono in questo mondo, ed è giusto combattere per questo” - Il Signore degli Anelli",
  "“Così continuiamo a remare, barche contro corrente” - Il Grande Gatsby",
  "“Non è nelle stelle che è conservato il nostro destino, ma in noi stessi” - Giulio Cesare",
  "“La felicità può essere trovata anche nei momenti più bui” - Harry Potter",
  "“Tutto ciò che dobbiamo decidere è cosa fare con il tempo che ci è dato” - Il Signore degli Anelli",
  "“Il mondo era suo, da leggere” - Un albero cresce a Brooklyn",
  "“Hai un cervello nella testa. Hai piedi nelle scarpe” - Oh, quante cose vedrai!",
  "“Anche la notte più buia finirà e il sole sorgerà” - I Miserabili",
  "“Non esiste amico più leale di un libro” - Ernest Hemingway",
  "“L'unico modo per uscire dal labirinto della sofferenza è perdonare” - Cercando Alaska",
  "“Non tutti quelli che vagano sono persi” - Il Signore degli Anelli",
  "“Non importa cosa si è nati, ma cosa si diventa” - Harry Potter",
  "“Il sole stesso è debole quando sorge per primo” - Grandi Speranze",
  "“Non è bello pensare che domani è un nuovo giorno senza ancora nessun errore?” - Anna dai capelli rossi",
  "“Di qualunque cosa siano fatte le nostre anime, la sua e la mia sono le stesse” - Cime Tempestose",
  "“Siamo fatti della stessa materia di cui sono fatti i sogni” - La Tempesta",
  "“Finché non ho temuto di perderla, non ho mai amato la lettura” - Il buio oltre la siepe",
  "“Sono le nostre scelte che mostrano ciò che siamo veramente” - Harry Potter",
  "“I libri sono una magia unicamente portatile” - Stephen King",
  "“Non c'è agonia più grande che portarsi dentro una storia non raccontata” - Io so perché canta l'uccello in gabbia",
  "“Tutta la saggezza umana è contenuta in queste due parole: aspetta e spera” - Il Conte di Montecristo",
  "“La vita mi sembra troppo breve per spenderla a nutrire animosità” - Jane Eyre",
  "“Il mondo spezza tutti, e poi molti sono forti nei punti spezzati” - Addio alle armi",
  "“Tutti i grandi erano una volta bambini” - Il Piccolo Principe",
  "“Amare un'altra persona è vedere il volto di Dio” - I Miserabili",
  "“La risposta non è nelle stelle ma in noi stessi” - Giulio Cesare",
  "“A volte le domande sono complicate e le risposte sono semplici” - Dr. Seuss",
  "“La terra ride nei fiori” - Ralph Waldo Emerson",
  "“Non capisci mai veramente una persona finché non ti infili nella sua pelle e non ci cammini dentro” - Il buio oltre la siepe",
  "“Ogni vita umana vale lo stesso, e vale la pena salvarla” - Harry Potter",
  "“Non puoi trovare una tazza di tè abbastanza grande o un libro abbastanza lungo per me” - C.S. Lewis",
  "“Definire è limitare” - Il ritratto di Dorian Gray",
  "“Un lettore vive mille vite prima di morire” - Le Cronache del Ghiaccio e del Fuoco",
  "“Il passato non è mai morto. Non è nemmeno passato” - William Faulkner",
  "“La mente è il suo proprio luogo, e in sé stessa può fare un paradiso dell'inferno” - Paradiso Perduto",
  "“Leggiamo e balliamo; questi due divertimenti non faranno mai male al mondo” - Voltaire",
  "“Il vero coraggio è quando sai di essere battuto prima di iniziare, ma inizi comunque” - Il buio oltre la siepe",
  "“È la possibilità di realizzare un sogno che rende la vita interessante” - L'Alchimista",
  "“Non c'è niente come restare a casa per un vero comfort” - Emma",
  "“Il mondo è pieno di cose ovvie che nessuno si prende la briga di osservare” - Sherlock Holmes",
  "“Una mente ha bisogno di libri come una spada ha bisogno di una cote” - Game of Thrones",
  "“Siamo tutti sciocchi in amore” - Orgoglio e Pregiudizio",
  "“Il futuro appartiene a coloro che credono nella bellezza dei propri sogni” - Anna dai capelli rossi",
  "“Il segreto per andare avanti è iniziare” - Mark Twain",
  "“Sono stati i libri a farmi sentire che forse non ero completamente solo” - L'Angelo Meccanico",
  "“Non devi vivere per sempre, devi solo vivere” - Tuck Everlasting",
  "“E ora che non devi essere perfetto, puoi essere buono” - La valle dell'Eden",
  "“Leggiamo per sapere che non siamo soli” - Viaggio in Inghilterra",
  "“Vivere sarà un'avventura terribilmente grande” - Peter Pan",
  "“Il mondo è davvero pieno di pericoli, e in esso ci sono molti luoghi oscuri; ma c'è ancora molto che è giusto” - Il Signore degli Anelli",
  "“Non serve a niente rifugiarsi nei sogni e dimenticarsi di vivere” - Harry Potter",
  "“Il coraggio si trova nei luoghi più improbabili” - La Compagnia dell'Anello",
  "“Sogniamo nei nostri momenti di veglia e camminiamo nel sonno” - La lettera scarlatta",
  "“Il tempo, che cambia le persone, non altera l'immagine che abbiamo conservato di loro” - Marcel Proust",
  "“Non c'è fascino pari alla tenerezza del cuore” - Emma",
  "“Sei stato mio amico. Questo di per sé è una cosa tremenda” - La tela di Carlotta",
  "“Tutto quello che dobbiamo decidere è cosa fare con il tempo che ci viene dato” - Le due torri",
  "“Apri gli occhi e guarda quello che puoi con essi prima che si chiudano per sempre” - Tutta la luce che non vediamo",
  "“Di qualunque cosa siano fatte le nostre anime, la sua e la mia sono le stesse” - Cime Tempestose",
  "“Attenzione; poiché sono senza paura, e quindi potente” - Frankenstein",
  "“Il mondo è pieno di cose per cui vale la pena combattere” - Lo Hobbit",
  "“Il sole non splende su di noi ma in noi” - John Muir",
  "“Non è mai troppo tardi per essere ciò che avresti potuto essere” - Middlemarch",
  "“Le persone generalmente vedono quello che cercano” - Il buio oltre la siepe",
  "“La luce splende nelle tenebre, e le tenebre non l'hanno sopraffatta” - La Bibbia",
  "“C'è una crepa in ogni cosa, è da lì che entra la luce” - Leonard Cohen (Beautiful Losers)",
  "“Siamo tutti nel fango, ma alcuni di noi guardano alle stelle” - Il ventaglio di Lady Windermere",
  "“Non tutti quelli che vagano sono persi” - La Compagnia dell'Anello",
  "“Non puoi restare nel tuo angolo della foresta aspettando che gli altri vengano da te” - Winnie the Pooh",
  "“Qui il mondo era silenzioso” - Una serie di sfortunati eventi",
  "“Le parole sono, nella mia non modesta opinione, la nostra fonte più inesauribile di magia” - Harry Potter",
  "“Ci vuole molto coraggio per affrontare i nostri nemici, ma altrettanto per affrontare i nostri amici” - Harry Potter",
  "“Anche i miracoli richiedono un po' di tempo” - Cenerentola",
  "“Essere appassionati di ballo era un passo certo verso l'innamoramento” - Orgoglio e Pregiudizio",
  "“La speranza è quella cosa piumata che si posa sull'anima” - Emily Dickinson",
  "“Alcuni infiniti sono più grandi di altri infiniti” - Colpa delle stelle",
  "“Tutto era bello e niente faceva male” - Mattatoio n. 5",
  "“Gli unici limiti per il domani sono i dubbi che abbiamo oggi” - Il vecchio e il mare",
  "“È solo con la gratitudine che la vita diventa ricca” - I fratelli Karamazov",
  "“Il modo migliore per scoprire se puoi fidarti di qualcuno è dargli fiducia” - Fiesta (Il sole sorge ancora)",
  "“Non c'è niente di buono o cattivo, ma è il pensiero a renderlo tale” - Amleto",
  "“Siamo ciò che crediamo di essere” - Don Chisciotte",
  "“Oserò disturbare l'universo?” - Il canto d'amore di J. Alfred Prufrock",
  "“Lo scopo della vita è vivere in accordo con la natura” - Zenone di Cizio (citato in Meditazioni)",
  "“Il passato è un fantasma, il futuro un sogno, e tutto ciò che abbiamo è ora” - Il nome del vento",
  "“Tutto ciò che puoi immaginare è reale” - Il ritratto di Dorian Gray",
  "“Finché non ho temuto di perderla, non ho mai amato la lettura” - Il buio oltre la siepe",
  "“Un uomo è solo il prodotto dei suoi pensieri; ciò che pensa, diventa” - Gandhi (Giovane India)",
  "“Dopo tutto, domani è un altro giorno” - Via col vento",
  "“Niente è impossibile, la parola stessa dice 'Io sono possibile!' (I'm possible)” - Colazione da Tiffany",
  "“Alla fine, siamo tutti storie. Fa' solo in modo che sia una bella storia” - Doctor Who (Romanzi)",
  "“Ogni cosa ha la sua bellezza, ma non tutti la vedono” - I Dialoghi (Confucio)",
  "“Ci sono cose molto, molto migliori davanti a noi di qualsiasi cosa lasciamo indietro” - L'ultima battaglia",
  "“Senza pioggia, non ci sarebbe arcobaleno” - Il mago di Oz",
  "“Un giorno troverò le parole giuste, e saranno semplici” - Big Sur",
  "“Casa è la parola più bella che ci sia” - La piccola casa nella prateria",
  "“La luce pensa di viaggiare più veloce di qualsiasi cosa, ma si sbaglia” - Buona Apocalisse a tutti!",
  "“Più leggi, più cose saprai” - Dr. Seuss",
  "“Un singolo sogno è più potente di mille realtà” - Il Signore degli Anelli",
  "“L'inizio è sempre oggi” - Mary Shelley",
  "“Niente finisce mai in modo poetico. Finisce e noi lo trasformiamo in poesia” - Il sole e i suoi fiori",
  "“Tutte le fini sono anche inizi. Solo che non lo sappiamo in quel momento” - Le cinque persone che incontri in cielo",
  "“La speranza sorride dalla soglia dell'anno a venire” - Alfred Lord Tennyson",
  "“È solo quando dimentichiamo tutto il nostro sapere che cominciamo a conoscere” - Walden",
  "“Alcuni libri ci lasciano liberi e alcuni libri ci rendono liberi” - Ralph Waldo Emerson",
  "“Il mondo è davanti a te, e non devi prenderlo o lasciarlo com'era quando sei arrivato” - James Baldwin",
  "“La magia è sempre nei dettagli” - Il dio delle piccole cose",
  "“Com'è meraviglioso che nessuno abbia bisogno di aspettare un solo momento prima di iniziare a migliorare il mondo” - Il diario di Anne Frank",
  "“Niente dietro di me, tutto davanti a me, come sempre sulla strada” - Sulla strada",
  "“La vita è un'avventura audace o niente del tutto” - La porta aperta",
  "“C'è una sorta di magia nell'andare lontano e poi tornare cambiati” - Il giardino segreto",
  "“Un bambino, un insegnante, un libro, una penna possono cambiare il mondo” - Io sono Malala",
  "“Il futuro appartiene a coloro che credono nella bellezza dei propri sogni” - Anna dai capelli rossi",
  "“Le favole sono più che vere: non perché ci dicono che esistono i draghi, ma perché ci dicono che i draghi possono essere sconfitti” - Coraline",
  "“Non è vero che le persone smettono di inseguire i sogni perché invecchiano, invecchiano perché smettono di inseguire i sogni” - L'Alchimista",
  "“Amare un'altra persona è vedere il volto di Dio” - I Miserabili",
  "“Tutto ciò che hai sempre desiderato è dall'altra parte della paura” - Il vecchio e il mare",
  "“Il segreto della vita, però, è cadere sette volte e rialzarsi otto” - L'Alchimista",
  "“L'anima si tinge del colore dei suoi pensieri” - Meditazioni",
  "“Non sei mai troppo vecchio per fissare un altro obiettivo o per sognare un nuovo sogno” - Le cronache di Narnia",
  "“I libri sono specchi: vedi in essi solo ciò che hai già dentro di te” - L'ombra del vento",
  "“Le cose semplici sono anche le cose più straordinarie” - L'Alchimista",
  "“L'universo è fatto di storie, non di atomi” - Il taccuino d'oro",
  "“La vita cambia velocemente. La vita cambia in un istante” - L'anno del pensiero magico",
  "“Non c'è niente di più necessario della speranza” - Racconto di due città",
  "“Non tutti quelli che vagano sono persi” - Il Signore degli Anelli",
  "“Per sapere chi ti comanda, scopri semplicemente chi non ti è permesso criticare” - Voltaire",
  "“Era il migliore dei tempi, era il peggiore dei tempi” - Racconto di due città",
  "“Sono radicata, ma fluisco” - Le onde",
  "“Siamo tutti rotti, è così che entra la luce” - Beautiful Losers",
  "“Il mondo ti dà così tanto dolore e tu sei qui a trasformarlo in oro” - Il sole e i suoi fiori",
  "“Non si può ridere sempre di un uomo senza inciampare ogni tanto in qualcosa di spiritoso” - Orgoglio e Pregiudizio",
  "“Non dobbiamo mai vergognarci delle nostre lacrime” - Grandi Speranze",
  "“Non puoi vivere la tua vita per altre persone” - Le pagine della nostra vita",
  "“Le storie sono creature selvagge, disse il mostro” - Sette minuti dopo la mezzanotte",
  "“Si è sempre trattato di speranza” - La ladra di libri",
  "“Ogni cuore umano è una storia che aspetta di essere letta” - Il circo della notte",
  "“Siamo tutti viaggiatori nella natura selvaggia di questo mondo” - La fiera della vanità",
  "“Non importa quanto stretto sia il passaggio, quanto piena di castighi la pergamena” - Invictus",
  "“Non esistono amicizie più rapide o più salde di quelle formate tra persone che amano gli stessi libri” - Il giro di vite",
  "“Non è mai troppo tardi per essere gentili” - Anna dai capelli rossi",
  "“Non temere la grandezza” - La dodicesima notte",
  "“Dimentichi quello che vuoi ricordare e ricordi quello che vuoi dimenticare” - La strada",
  "“Senza storie, impazziremmo” - L'oceano in fondo al sentiero",
  "“A volte devi viaggiare lontano per trovare ciò che è vicino” - Il mago di Earthsea",
  "“Non c'è divertimento come la lettura” - Orgoglio e Pregiudizio",
  "“Il vento era un torrente di oscurità tra gli alberi rafficati” - L'autostrada (The Highwayman)",
  "“Non puoi fuggire da te stesso spostandoti da un posto all'altro” - Fiesta (Il sole sorge ancora)",
  "“Le parole sono vita, e leggerle è vivere due volte” - La ladra di libri",
  "“Leggi per vivere” - Gustave Flaubert",
  "“Devi scrivere la tua prima bozza con il cuore” - On Writing",
  "“Il mondo era suo, da leggere” - Un albero cresce a Brooklyn",
  "“Nel momento in cui apri un libro, entri in un altro mondo” - Cuore d'inchiostro",
  "“Imparare a leggere è accendere un fuoco” - Victor Hugo",
  "“Non esiste amico più leale di un libro” - Ernest Hemingway",
  "“I libri sono gli amici più silenziosi e costanti” - Charles W. Eliot",
  "“La lettura è essenziale per coloro che cercano di elevarsi al di sopra dell'ordinario” - Jim Rohn",
  "“La persona che merita più pietà è una persona sola in un giorno di pioggia che non sa leggere” - Benjamin Franklin",
  "“La biblioteca è abitata da spiriti che escono dalle pagine di notte” - Isabel Allende",
  "“Una stanza senza libri è come un corpo senz'anima” - Marco Tullio Cicerone",
  "“La lettura di tutti i buoni libri è come una conversazione con le menti migliori dei secoli passati” - Cartesio",
  "“Questo è il bello dei libri. Ti permettono di viaggiare senza muovere i piedi” - L'omonimo",
  "“Ogni libro era un mondo a sé stante” - Fahrenheit 451",
  "“I libri la trasportavano in nuovi mondi” - Matilde",
  "“La lettura ci dà un posto dove andare quando dobbiamo rimanere dove siamo” - Mason Cooley",
  "“C'è più tesoro nei libri che in tutto il bottino dei pirati sull'Isola del Tesoro” - Walt Disney",
  "“Ho sempre immaginato che il paradiso fosse una specie di biblioteca” - Jorge Luis Borges",
  "“L'uomo che non legge non ha alcun vantaggio sull'uomo che non sa leggere” - Mark Twain",
  "“Un libro è un sogno che tieni tra le mani” - Neil Gaiman",
  "“Leggere è partenza e arrivo” - Terri Guillemets",
  "“Una volta che impari a leggere, sarai libero per sempre” - Frederick Douglass",
  "“I libri sono una magia unicamente portatile” - Stephen King",
  "“La storia è sempre migliore quando la leggi tu stesso” - La ladra di libri",
  "“Leggere un libro è come mangiare una patatina” - Diane Duane",
  "“L'amore per lo studio, gli angoli appartati e tutta la dolce serenità dei libri” - Henry Wadsworth Longfellow",
  "“Un grande libro dovrebbe lasciarti con molte esperienze” - William Styron",
  "“Alcune storie restano con noi per sempre” - Lo Hobbit",
  "“La lettura ci porta amici sconosciuti” - Honoré de Balzac",
  "“Un libro è la prova che gli esseri umani possono fare magie” - Carl Sagan",
  "“La letteratura è il modo più gradevole di ignorare la vita” - Fernando Pessoa",
  "“Il mondo appartiene a coloro che leggono” - Rick Holland",
  "“I più cari del tempo, i più forti amici dell'anima: i libri” - Emily Dickinson",
  "“Non posso vivere senza libri” - Thomas Jefferson",
  "“Ci sono crimini peggiori del bruciare libri. Uno di questi è non leggerli” - Ray Bradbury",
  "“I libri sono fari eretti nel grande mare del tempo” - E.P. Whipple",
  "“Nessun intrattenimento è economico come la lettura” - Mary Wortley Montagu",
  "“Un libro è un regalo che puoi aprire ancora e ancora” - Garrison Keillor",
  "“La lettura fornisce alla mente solo i materiali della conoscenza” - John Locke",
  "“Più leggi, più cose saprai” - Dr. Seuss",
  "“Una parola dopo una parola dopo una parola è potere” - Margaret Atwood",
  "“Un libro deve essere l'ascia per il mare ghiacciato dentro di noi” - Franz Kafka",
  "“Non ci sono forse giorni della nostra infanzia che abbiamo vissuto così pienamente come quelli che abbiamo passato con un libro preferito” - Marcel Proust",
  "“Leggere è un esercizio di empatia” - Malorie Blackman",
  "“I libri allenano la tua immaginazione a pensare in grande” - Little Golden Book",
  "“L'uomo che non legge nulla è più istruito dell'uomo che non legge altro che giornali” - The Writings of Thomas Jefferson",
  "“Leggere è sognare ad occhi aperti” - Sogni di Carta",
  "“I libri sono gli specchi dell'anima” - To the Lighthouse",
  "“La gioia di leggere è scoprire mondi che non sapevi esistessero” - L'Alchimista",
  "“Tra le pagine di un libro è un posto incantevole dove stare” - Raccolta di Aforismi",
  "“Lasciate ogne speranza, voi ch'intrate” - Divina Commedia",
  "“Fatti non foste a viver come bruti, ma per seguir virtute e canoscenza” - Inferno",
  "“Amor, ch'a nullo amato amar perdona” - Inferno",
  "“L'amor che move il sole e l'altre stelle” - Paradiso",
  "“Questo matrimonio non s'ha da fare” - I Promessi Sposi",
  "“Il coraggio, uno, se non ce l'ha, mica se lo può dare” - I Promessi Sposi",
  "“La sventurata rispose” - I Promessi Sposi",
  "“Addio, monti sorgenti dall'acque” - I Promessi Sposi",
  "“Sempre caro mi fu quest'ermo colle” - L'Infinito",
  "“E il naufragar m'è dolce in questo mare” - L'Infinito",
  "“Che fai tu, luna, in ciel? dimmi, che fai, silenziosa luna?” - Canto notturno di un pastore errante dell'Asia",
  "“La noia è in qualche modo il più sublime dei sentimenti umani” - Zibaldone",
  "“Così è (se vi pare)” - Così è (se vi pare)",
  "“Imparerai a tue spese che nel lungo tragitto della vita incontrerai tante maschere e pochi volti” - Il Fu Mattia Pascal",
  "“La vita non è né brutta né bella, ma è originale” - La coscienza di Zeno",
  "“Quella che sto fumando... è l’ultima sigaretta” - La coscienza di Zeno",
  "“Se vogliamo che tutto rimanga come è, bisogna che tutto cambi” - Il Gattopardo",
  "“Prendete la vita con leggerezza, che leggerezza non è superficialità, ma planare sulle cose dall'alto” - Lezioni Americane",
  "“Le città come i sogni sono costruite di desideri e di paure” - Le città invisibili",
  "“L'inferno dei viventi non è qualcosa che sarà; se ce n'è uno, è quello che è già qui” - Le città invisibili",
  "“Cercare e saper riconoscere chi e cosa, in mezzo all'inferno, non è inferno, e farlo durare, e dargli spazio” - Le città invisibili",
  "“Chi non legge, a 70 anni avrà vissuto una sola vita: la propria. Chi legge avrà vissuto 5000 anni” - Il nome della rosa",
  "“Stat rosa pristina nomine, nomina nuda tenemus” - Il nome della rosa",
  "“Non sei fregato veramente finché hai da parte una buona storia, e qualcuno a cui raccontarla” - Novecento",
  "“Non si è mai lontani abbastanza per trovarsi” - Oceano Mare",
  "“Considerate se questo è un uomo, che lavora nel fango, che non conosce pace” - Se questo è un uomo",
  "“Auschwitz è fuori di noi, ma è intorno a noi” - Se questo è un uomo",
  "“Verrà la morte e avrà i tuoi occhi” - Verrà la morte e avrà i tuoi occhi",
  "“Un paese ci vuole, non fosse che per il gusto di andarsene via” - La luna e i falò",
  "“Non si finisce mai di imparare, e non si finisce mai di sbagliare” - Il mestiere di vivere",
  "“M'illumino d'immenso” - Mattina",
  "“Si sta come d'autunno sugli alberi le foglie” - Soldati",
  "“Spesso il male di vivere ho incontrato” - Ossi di seppia",
  "“Non chiederci la parola che squadri da ogni lato” - Ossi di seppia",
  "“Bisogna fare la propria vita come si fa un'opera d'arte” - Il Piacere",
  "“Memento audere semper” - Il Piacere",
  "“Il fine giustifica i mezzi” - Il Principe",
  "“Le donne, i cavallier, l'arme, gli amori” - Orlando Furioso",
  "“Erano i capei d’oro a l’aura sparsi” - Canzoniere",
  "“L'indifferenza è il peso morto della storia” - La città futura",
  "“Ognuno sta solo sul cuor della terra trafitto da un raggio di sole: ed è subito sera” - Ed è subito sera",
  "“Il mondo è un bel libro, ma poco serve a chi non lo sa leggere” - Le commedie",
  "“Malpelo si chiamava così perché aveva i capelli rossi” - Rosso Malpelo",
  "“A futura memoria” - Il giorno della civetta",
  "“La Sicilia è un'isola, e questo definisce tutto” - Il giorno della civetta",
  "“Io so i nomi dei responsabili... Ma non ho le prove” - Scritti corsari",
  "“Sono un poeta. Un poeta è un minatore di parole” - Poesie in forma di rosa",
  "“La Storia non è maestra di niente che ci riguardi” - La Storia",
  "“L'infanzia è un paradiso perduto” - L'isola di Arturo",
  "“Noi siamo le nostre piccole storie” - Le piccole virtù",
  "“Ciò che nella vita rimane, non sono i doni materiali, ma i ricordi che abbiamo lasciato” - Corpo d'amore",
  "“La peggior solitudine è non essere a proprio agio con se stessi” - Vuoto d'amore",
  "“Sognare è l'unica cosa che ci rimane da fare gratis” - Ballate non pagate",
  "“Siamo angeli con un'ala sola, possiamo volare solo abbracciati” - Così parlò Bellavista",
  "“Chi ha paura muore ogni giorno, chi non ha paura muore una volta sola” - Interventi e scritti",
  "“Gli uomini passano, le idee restano. Restano le loro tensioni morali” - Cose di Cosa Nostra",
  "“Raccontare è resistere” - Gomorra",
  "“Vieni via con me” - Vieni via con me",
  "“Le parole sono importanti” - Palombella Rossa",
  "“Va' dove ti porta il cuore” - Va' dove ti porta il cuore",
  "“Scrivere è l'unico modo per vivere due volte” - Va' dove ti porta il cuore",
  "“Il mare non ha paese” - Il contrario di uno",
  "“Considero valore ogni forma di vita, la neve, la fragola, la mosca” - Valore",
  "“Il peso delle parole è il silenzio da cui provengono” - In nome della madre",
  "“Non c'è nulla di più terribile che perdere il controllo” - L'amica geniale",
  "“Le cose migliori si ottengono solo con il massimo sforzo” - Rime e ritmi",
  "“La nebbia a gl'irti colli...” - San Martino",
  "“Il sognatore è un uomo con i piedi fortemente appoggiati sulle nuvole” - Diario degli errori",
  "“La situazione politica in Italia è grave, ma non è seria” - Diario degli errori",
  "“Ahi serva Italia, di dolore ostello, nave sanza nocchiere in gran tempesta” - Purgatorio",
  "“Il mondo è fango” - A se stesso",
  "“Uno, nessuno e centomila” - Uno, nessuno e centomila",
  "“La vita è un’enorme pupazzata” - Il berretto a sonagli",
  "“La coscienza è un ragno che tesse la sua tela nell'ombra” - La coscienza di Zeno",
  "“Noi fummo i Gattopardi, i Leoni; quelli che ci sostituiranno saranno gli sciacalletti, le iene” - Il Gattopardo",
  "“L'Italia è un paese pronto a piegarsi ai vincitori” - Il Gattopardo",
  "“Se comprendere è impossibile, conoscere è necessario” - Se questo è un uomo",
  "“Tutti i libri del mondo non ti danno la felicità, ma ti riportano dolcemente a te stesso” - Siddhartha",
  "“Dove si bruciano i libri, si finisce per bruciare anche gli uomini” - Almansor",
  "“La felicità è una cosa piccola” - Un altro giro di giostra",
  "“Tutto quello che cerchi è già dentro di te” - Lettere contro la guerra",
  "“La vera rivoluzione comincia da se stessi” - La fine è il mio inizio",
  "“Il nome di una donna è più importante del nome di una città” - Conversazione in Sicilia",
  "“Il comunismo è una malattia del cuore” - Vino e pane",
  "“Che cos'è un uomo in rivolta? Un uomo che dice no” - L'uomo in rivolta",
  "“L'indifferenza è il più grande peccato” - Gli indifferenti",
  "“Il futuro ha un cuore antico” - Cristo si è fermato a Eboli",
  "“Non si possiede mai un gatto. Semmai, si è ammessi alla sua vita” - Due di due",
  "“Dio ci ha dato la memoria così possiamo avere le rose a dicembre” - Peter Pan",
  "“Io non ho paura” - Io non ho paura",
  "“La roba non è di chi l'ha, ma di chi la sa godere” - Mastro-don Gesualdo",
  "“C’è qualcosa di nuovo oggi nel sole, anzi d’antico” - L'aquilone",
  "“La vita fugge, et non s’arresta una hora” - Canzoniere",
  "“Umana cosa è aver compassione degli afflitti” - Decameron",
  "“La più grande sfortuna è non essere mai stati sfortunati” - Il Principe",
  "“Meglio essere temuti che amati, se non si può essere entrambi” - Il Principe",
  "“C'è un solo tipo di successo: quello di fare della propria vita ciò che si desidera” - Walden",
  "“Il mondo è di chi non ha paura” - Proverbi italiani",
  "“Vivere non è necessario, navigare è necessario” - Navigare necesse est"
];

let quotesPersian = [
"«تنها با قلب است که می‌توان درست دید.» - شازده کوچولو",
"«وقتی شک می‌کنی که می‌توانی پرواز کنی، برای همیشه توانش را از دست می‌دهی.» - پیتر پن",
"«فردا همیشه تازه است، هنوز هیچ اشتباهی در آن نیست.» - آنی از گرین گیبلز",
"«در این دنیا خوبی وجود دارد و ارزش جنگیدن دارد.» - ارباب حلقه‌ها",
"«و ما همچنان پیش می‌رویم، قایق‌ها علیه جریان آب.» - گتسبی بزرگ",
"«سرنوشت ما در ستارگان نیست، بلکه در دست خود ماست.» - ژولیوس سزار",
"«خوشبختی حتی در تاریک‌ترین زمان‌ها هم می‌تواند یافت شود.» - هری پاتر",
"«تنها چیزی که باید تصمیم بگیریم، این است که با زمانی که به ما داده شده چه کنیم.» - ارباب حلقه‌ها",
"«دنیا از آنِ او بود که می‌خواند.» - درختی در بروکلین رشد می‌کند",
"«مغزی در سرت داری. پایی در کفشت داری.» - آه، جاهایی که خواهی رفت!",
"«حتی تاریک‌ترین شب هم سرانجام پایان می‌یابد و خورشید طلوع می‌کند.» - بینوایان",
"«هیچ دوستی وفادارتر از کتاب نیست.» - ارنست همینگوی",
"«تنها راه خروج از هزارتوی رنج، بخشیدن است.» - در جستجوی آلاسکا",
"«همهٔ آن‌هایی که سرگردانند، گم نشده‌اند.» - ارباب حلقه‌ها",
"«مهم نیست که با چه متولد شده‌ای، مهم این است که به چه تبدیل می‌شوی.» - هری پاتر",
"«خورشید خودش ضعیف است وقتی تازه طلوع می‌کند.» - آرزوهای بزرگ",
"«آیا زیبا نیست فکر کنیم فردا روزی تازه است بدون هیچ اشتباهی؟» - آنی از گرین گیبلز",
"«هر چه از روح ما ساخته شده باشد، روح من و او یکی است.» - بلندی‌های بادگیر",
"«ما از همان موادی ساخته شده‌ایم که رویاها از آن ساخته می‌شوند.» - طوفان",
"«تا زمانی که از دست دادنش را نترسیدم، هرگز دوست داشتن خواندن را نفهمیدم.» - کشتن مرغ مقلد",
"«این انتخاب‌های ما هستند که نشان می‌دهند واقعاً چه کسی هستیم.» - هری پاتر",
"«کتاب‌ها جادوی قابل‌حمل بی‌نظیری‌اند.» - استیون کینگ",
"«هیچ دردی بزرگ‌تر از نگه داشتن داستانی ناگفته در درون خود نیست.» - می‌دانم چرا پرنده در قفس می‌خواند",
"«تمام خرد انسان در دو کلمه خلاصه می‌شود – صبر و امید.» - کنت مونت کریستو",
"«زندگی برای کینه‌ورزی بیش از حد کوتاه است.» - جین ایر",
"«دنیا همه را می‌شکند، و پس از آن، بسیاری در جاهای شکسته قوی‌تر می‌شوند.» - وداع با اسلحه",
"«تمام بزرگسالان زمانی کودک بوده‌اند.» - شازده کوچولو",
"«دوست داشتن دیگری یعنی دیدن چهرهٔ خدا.» - بینوایان",
"«پاسخ در ستارگان نیست، بلکه در خود ماست.» - ژولیوس سزار",
"«گاهی پرسش‌ها پیچیده‌اند و پاسخ‌ها ساده.» - دکتر سوس",
"«زمین در گل‌ها می‌خندد.» - رالف والدو امرسون",
"«تو واقعاً هیچ انسانی را درک نمی‌کنی تا زمانی که در پوست او راه بروی و از درونش ببینی.» - کشتن مرغ مقلد",
"«هر زندگی انسانی ارزشی برابر دارد و ارزش نجات دادن دارد.» - هری پاتر",
"«نه فنجانی چای می‌تواند برایم بزرگ‌تر باشد و نه کتابی طولانی‌تر.» - سی.اس. لوئیس",
"«تعریف کردن یعنی محدود کردن.» - تصویر دوریان گری",
"«خواننده پیش از مرگش هزار زندگی می‌زید.» - نغمه یخ و آتش",
"«گذشته هرگز نمی‌میرد، حتی گذشته نیست.» - ویلیام فاکنر",
"«ذهن مکان خودش است و می‌تواند از جهنم بهشت بسازد یا از بهشت جهنم.» - بهشت گمشده",
"«بخوانیم و برقصیم؛ این دو سرگرمی هرگز به جهان آسیبی نمی‌رسانند.» - ولتر",
"«شجاعت واقعی وقتی است که می‌دانی شکست می‌خوری ولی باز هم آغاز می‌کنی.» - کشتن مرغ مقلد",
"«امکان تحقق رؤیاهاست که زندگی را جالب می‌کند.» - کیمیاگر",
"«هیچ چیز مانند خانه برای آسایش واقعی نیست.» - اما",
"«دنیا پر از چیزهای آشکاری است که هیچ‌کس آن‌ها را نمی‌بیند.» - شرلوک هلمز",
"«ذهن به کتاب نیاز دارد، همان‌طور که شمشیر به سنگ تیزکن.» - بازی تاج و تخت",
"«ما همگی در عشق احمقیم.» - غرور و تعصب",
"«آینده از آن کسانی است که به زیبایی رویاهایشان ایمان دارند.» - آنی از گرین گیبلز",
"«راز پیشرفت، آغاز کردن است.» - مارک تواین",
"«کتاب‌ها بودند که به من احساس کردند شاید کاملاً تنها نباشم.» - فرشته ساعت",
"«لازم نیست برای همیشه زندگی کنی، فقط باید واقعاً زندگی کنی.» - توک جاودان",
"«و حالا که مجبور نیستی کامل باشی، می‌توانی خوب باشی.» - شرق بهشت",
"«ما می‌خوانیم تا بدانیم تنها نیستیم.» - سایه‌سرزمین‌ها",
"«زندگی کردن خود، ماجراجویی بزرگی خواهد بود.» - پیتر پن",
"«دنیا واقعاً پر از خطر است، و در آن مکان‌های تاریک بسیاری وجود دارد؛ اما هنوز چیزهای زیبای فراوانی هست.» - ارباب حلقه‌ها",
"«خوب نیست که فقط در رویاها زندگی کنیم و زندگی واقعی را فراموش کنیم.» - هری پاتر",
"«شجاعت در جاهایی غیرمنتظره یافت می‌شود.» - یاران حلقه",
"«ما در لحظات بیداری خود رؤیا می‌بینیم و در خواب راه می‌رویم.» - حرف‌نامه سرخ",
"«زمان، که انسان‌ها را تغییر می‌دهد، تصویری را که از آن‌ها در ذهن داریم عوض نمی‌کند.» - مارسل پروست",
"«هیچ جذابیتی هم‌سنگ مهربانی دل نیست.» - اما",
"«تو دوستم بوده‌ای. همین خودش چیز فوق‌العاده‌ای است.» - تار شارلوت",
"«تنها باید تصمیم بگیریم با زمان داده‌شده به ما چه کنیم.» - دو برج",
"«چشمانت را باز کن و ببین تا قبل از آنکه برای همیشه بسته شوند.» - نوری که نمی‌توانیم ببینیم",
"«روح من و او از یک جنس ساخته شده‌اند.» - بلندی‌های بادگیر",
"«مراقب باش؛ زیرا من بی‌باکم، و به همین دلیل قدرتمند.» - فرانکشتاین",
"«دنیا پر از چیزهایی است که ارزش جنگیدن دارند.» - هابیت",
"«خورشید بر ما نمی‌تابد، بلکه درون ما می‌تابد.» - جان مویر",
"«هیچ‌گاه برای تبدیل شدن به آنچه باید باشی دیر نیست.» - میدل‌مارچ",
"«مردم معمولاً همان چیزی را می‌بینند که به دنبالش هستند.» - کشتن مرغ مقلد",
"«نور در تاریکی می‌تابد، و تاریکی بر آن چیره نشده است.» - انجیل مقدس",
"«در هر چیزی شکافی هست، همان‌جاست که نور وارد می‌شود.» - لئونارد کوهن (زیبای شکست‌خورده)",
"«همه در جوی کثافتیم، اما بعضی از ما به ستارگان می‌نگریم.» - بانو ویندرمر",
"«همهٔ آن‌هایی که سرگردانند، گم نشده‌اند.» - یاران حلقه",
"«نمی‌توانی در گوشهٔ جنگلت بنشینی و منتظر باشی دیگران نزدت بیایند.» - وینی د پو",
"«دنیا اینجا آرام بود.» - مجموعه‌ای از اتفاقات ناگوار",
"«کلمات، به نظر من، منبعی بی‌پایان از جادو هستند.» - هری پاتر",
"«شجاعت بسیاری لازم است تا در برابر دشمنانمان بایستیم، اما به همان اندازه برای ایستادن مقابل دوستانمان نیز.» - هری پاتر",
"«حتی معجزه‌ها هم کمی زمان می‌خواهند.» - سیندرلا",
"«دوست داشتن رقص، قدمی به سوی عاشق شدن است.» - غرور و تعصب",
"«امید همان پرنده‌ای است با پرهایی در روح.» - امیلی دیکینسون",
"«برخی بی‌نهایت‌ها بزرگ‌تر از بی‌نهایت‌های دیگرند.» - بخت ستارگان ما",
"«همه‌چیز زیبا بود و هیچ دردی نبود.» - سلاخ‌خانه شماره پنج",
"«تنها محدودیت‌های فردا، تردیدهای امروز ماست.» - پیرمرد و دریا",
"«تنها با سپاسگزاری است که زندگی غنی می‌شود.» - برادران کارامازوف",
"«بهترین راه برای فهمیدن اینکه می‌توانی به کسی اعتماد کنی، اعتماد کردن است.» - خورشید نیز طلوع می‌کند",
"«هیچ چیز نه خوب است نه بد، این فکر ماست که آن را می‌سازد.» - هملت",
"«ما همانیم که باور داریم هستیم.» - دن‌کیشوت",
"«آیا جرأت دارم جهان را برهم زنم؟» - آواز عاشقانه جی. آلفرد پروفروک",
"«هدف زندگی هماهنگی با طبیعت است.» - زنون اهل کیتیوم (تأملات)",
"«گذشته روحی است، آینده رؤیایی، و تنها چیزی که داریم اکنون است.» - نام باد",
"«هر چه بتوانی تصور کنی، واقعی است.» - تصویر دوریان گری",
"«تا زمانی که از دست دادنش نترسیدم، هرگز دوست داشتن خواندن را نفهمیدم.» - کشتن مرغ مقلد",
"«انسان محصول افکار خویش است؛ آنچه می‌اندیشد، همان می‌شود.» - گاندی (هند جوان)",
"«به هر حال، فردا روزی دیگر است.» - بربادرفته",
"«هیچ چیز غیرممکن نیست، خود کلمه می‌گوید من ممکنم!» - صبحانه در تیفانی",
"«در پایان، ما همه داستانیم. فقط آن را خوب بساز.» - دکتر هو: ماجراهای رمان",
"«هر چیزی زیبایی دارد، اما همه آن را نمی‌بینند.» - گفتارها (کنفوسیوس)",
"«چیزهای بسیار بهتری در پیش رو داریم تا آنچه پشت سر می‌گذاریم.» - آخرین نبرد",
"«بدون باران، رنگین‌کمانی هم نخواهد بود.» - جادوگر شهر اُز",
"«روزی کلمات درست را خواهم یافت و ساده خواهند بود.» - بیگ سور",
"«خانه زیباترین واژه‌ای است که وجود دارد.» - خانه کوچک در چمنزار"
]

let quotesHindi = [
    "सही तरह से देखने की शक्ति केवल दिल से ही आती है। - छोटा राजकुमार",
    "जिस पल तुम उड़ने पर शक करते हो, उसी पल तुम हमेशा के लिए उड़ने की क्षमता खो देते हो। - पीटर पैन",
    "कल हमेशा नया होता है, उसमें अब तक कोई गलती नहीं हुई होती। - ऐन ऑफ ग्रीन गेबल्स",
    "इस दुनिया में कुछ अच्छाई है, और उसके लिए लड़ना सार्थक है। - अंगूठे के छल्ले की अंगूठी",
    "तो हम आगे बढ़ते हैं, धाराओं के विरुद्ध नौकाओं की तरह। - महान गैट्सबी",
    "हमारा भाग्य सितारों में नहीं, बल्कि हमारे अपने हाथों में है। - जूलियस सीज़र",
    "सबसे अंधेरे समय में भी खुशी पाई जा सकती है। - हैरी पॉटर",
    "हमें बस यह तय करना है कि हमें दिए गए समय के साथ क्या करना है। - अंगूठे के छल्ले की अंगूठी",
    "पढ़ने के लिए पूरी दुनिया उसकी थी। - ब्रुकलिन में एक पेड़ उगता है",
    "तुम्हारे सिर में दिमाग है, तुम्हारे जूतों में पैर हैं। - ओह, तुम जहाँ भी जाओगे!",
    "सबसे अंधेरी रात भी खत्म होगी और सूरज फिर उगेगा। - ले मिज़रेबल्स",
    "किताब जितना वफ़ादार कोई दोस्त नहीं होता। - अर्नेस्ट हेमिंग्वे",
    "दुखों की भूलभुलैया से निकलने का एकमात्र रास्ता है – क्षमा करना। - अलास्का की तलाश",
    "जो भटकते हैं, वे सभी खोए हुए नहीं होते। - अंगूठे के छल्ले की अंगूठी",
    "किसी का जन्म क्या है, यह मायने नहीं रखता; वह क्या बनता है, यही असली बात है। - हैरी पॉटर",
    "जब सूरज पहली बार उगता है, तो वह खुद भी कमजोर होता है। - महान अपेक्षाएँ",
    "क्या यह सोचकर अच्छा नहीं लगता कि कल एक नया दिन है, जिसमें अब तक कोई गलती नहीं हुई? - ऐन ऑफ ग्रीन गेबल्स",
    "हमारी आत्माएं चाहे जिस चीज़ से बनी हों, उसकी और मेरी एक ही हैं। - वुथरिंग हाइट्स",
    "हम उसी चीज़ से बने हैं जिससे सपने बनते हैं। - तूफ़ान",
    "जब तक मुझे डर नहीं लगा कि मैं इसे खो दूंगा, तब तक मैंने पढ़ने से कभी प्रेम नहीं किया। - एक परिंदा मारना",
    "हमारे चुनाव ही बताते हैं कि हम वास्तव में कौन हैं। - हैरी पॉटर",
    "किताबें एक अनोखा और साथ ले जाने योग्य जादू हैं। - स्टीफ़न किंग",
    "सबसे बड़ा दुख वह कहानी है जो कभी कही नहीं गई। - मैं क्यों क्यूँ पंछी गाती है",
    "सारी मानव बुद्धि दो शब्दों में निहित है – प्रतीक्षा और आशा। - मोंटे क्रिस्टो की गिनती",
    "जीवन इतना छोटा है कि उसे नफरत में बर्बाद नहीं किया जा सकता। - जेन एयरे",
    "दुनिया हर किसी को तोड़ती है, लेकिन टूटने के बाद कई लोग मज़बूत बन जाते हैं। - विदा के हाथ",
    "सभी बड़े लोग कभी बच्चे थे। - छोटा राजकुमार",
    "किसी और से प्रेम करना ईश्वर का चेहरा देखने जैसा है। - ले मिज़रेबल्स",
    "उत्तर सितारों में नहीं, हमारे भीतर है। - जूलियस सीज़र",
    "कभी-कभी प्रश्न कठिन होते हैं, पर उत्तर सरल। - डॉ. सीउस",
    "धरती फूलों में हँसती है। - राल्फ वाल्डो इमर्सन",
    "जब तक तुम किसी के स्थान पर खुद को नहीं रखोगे, तब तक उसे वास्तव में नहीं समझोगे। - एक परिंदा मारना",
    "हर मानव जीवन समान है और बचाए जाने योग्य है। - हैरी पॉटर",
    "मुझे इतनी बड़ी चाय नहीं मिलती जितनी मैं चाहता हूँ, और न इतनी लंबी किताब जितनी मुझे भाती है। - सी. एस. लुईस",
    "परिभाषित करना सीमित करना है। - डोरियन ग्रे की तस्वीर",
    "एक पाठक अपनी मृत्यु से पहले हज़ार जीवन जीता है। - एक आग और बर्फ का गीत",
    "अतीत कभी मरता नहीं, वह तो अभी भी हमारे साथ है। - विलियम फॉक्नर",
    "मन अपनी ही जगह है और स्वयं स्वर्ग को नरक बना सकता है या नरक को स्वर्ग। - पैराडाइज लॉस्ट",
    "आओ पढ़ें और नाचें; ये दोनों आनंद कभी दुनिया को नुकसान नहीं देंगे। - वोल्टेयर",
    "सच्चा साहस यह है कि जब तुम जानते हो कि तुम हार चुके हो, फिर भी शुरुआत करो। - एक परिंदा मारना",
    "जीवन को रोचक बनाने वाली चीज़ यह है कि सपने सच हो सकते हैं। - द अल्केमिस्ट",
    "असली सुकून घर पर रहने में है। - एम्मा",
    "दुनिया स्पष्ट चीज़ों से भरी है जिन्हें कोई नहीं देखता। - शर्लक होम्स",
    "तलवार को धार देने की तरह, मन को किताबों की आवश्यकता होती है। - गेम ऑफ थ्रोन्स",
    "हम सभी प्रेम में मूर्ख हैं। - गर्व और पूर्वाग्रह",
    "भविष्य उनका है जो अपने सपनों की सुंदरता पर विश्वास करते हैं। - ऐन ऑफ ग्रीन गेबल्स",
    "आगे बढ़ने का रहस्य है — शुरुआत करना। - मार्क ट्वेन",
    "किताबों ने मुझे यह महसूस कराया कि शायद मैं पूरी तरह अकेला नहीं हूँ। - क्लॉकवर्क एंजल",
    "तुम्हें हमेशा के लिए जीना नहीं है, तुम्हें बस जीना है। - टक एवरलास्टिंग",
    "अब जब तुम्हें परिपूर्ण नहीं होना, तब तुम अच्छे बन सकते हो। - ईस्ट ऑफ ईडेन",
    "हम पढ़ते हैं ताकि हमें यह महसूस हो कि हम अकेले नहीं हैं। - शैडो लैंड्स",
    "जीना एक बड़ा साहसिक कार्य है। - पीटर पैन",
       "दुनिया वास्तव में खतरों से भरी है, पर उसमें बहुत सुंदर चीज़ें भी हैं। - अंगूठे के छल्ले की अंगूठी",
       "सपनों में जीते रहना ठीक नहीं है और जीवन को भूल जाना भी। - हैरी पॉटर",
       "साहस अक्सर अप्रत्याशित स्थानों में मिलता है। - द फेलोशिप ऑफ द रिंग",
       "हम जागते हुए सपने देखते हैं और सोते हुए चलते हैं। - द स्कारलेट लेटर",
       "समय लोगों को बदल देता है, पर हमारे मन में उनकी छवि वही रहती है। - मार्सेल प्राउस्ट",
       "कोमल हृदय से बढ़कर कोई आकर्षण नहीं। - एम्मा",
       "तुम मेरे मित्र रहे हो। बस यही बहुत बड़ी बात है। - शार्लोट्स वेब",
       "हमें बस यह तय करना है कि हमें दिए गए समय के साथ क्या करना है। - द टू टावर्स",
       "अपनी आँखें खोलो और जब तक वे खुली हैं, जितना देख सको देखो। - ऑल द लाइट वी कैनॉट सी",
       "हमारी आत्माएँ चाहे जिस चीज़ से बनी हों, उसकी और मेरी एक ही हैं। - वुथरिंग हाइट्स",
       "सावधान रहो; क्योंकि मैं निडर हूँ, और इसलिए शक्तिशाली। - फ्रेंकस्टीन",
       "दुनिया लड़ने लायक चीज़ों से भरी है। - द हॉबिट",
       "सूरज हम पर नहीं बल्कि हमारे भीतर चमकता है। - जॉन म्यूर",
       "जो तुम बनना चाहते थे, बनने में कभी देर नहीं होती। - मिडलमार्च",
       "लोग आम तौर पर वही देखते हैं जो वे देखना चाहते हैं। - एक परिंदा मारना",
       "अंधकार में भी प्रकाश चमकता है, और अंधकार उसे परास्त नहीं कर पाता। - बाइबिल",
       "हर चीज़ में एक दरार होती है, और वहीं से रोशनी आती है। - लियोनार्ड कोहेन",
       "हम सब नाली में हैं, पर कुछ लोग सितारों की ओर देख रहे हैं। - लेडी विंडर्मेयर का फैन",
       "जो भटकते हैं, वे सभी खोए हुए नहीं होते। - द फेलोशिप ऑफ द रिंग",
       "तुम जंगल के कोने में बैठे रहकर यह उम्मीद नहीं कर सकते कि लोग तुमसे मिलने आएंगे। - विंनी द पूह",
       "दुनिया यहाँ शांत थी। - अ सीरीज़ ऑफ अनफॉर्चुननेट इवेंट्स",
       "शब्द, मेरी विनम्र राय में, जादू का सबसे अटूट स्रोत हैं। - हैरी पॉटर",
       "सच्ची बहादुरी यह है कि जब तुम अपने मित्रों के सामने खड़े होते हो। - हैरी पॉटर",
       "चमत्कारों को भी थोड़ा समय लगता है। - सिंड्रेला",
       "नृत्य के प्रति प्रेम होना प्रेम में पड़ने की पहली सीढ़ी है। - गर्व और पूर्वाग्रह",
       "आशा वह चीज़ है जो आत्मा में बैठी पंखों वाली चिड़िया है। - एमिली डिकिंसन",
       "कुछ अनंतताएँ दूसरों से बड़ी होती हैं। - द फॉल्ट इन अवर स्टार्स",
       "सब कुछ सुंदर था, और किसी को दुख नहीं था। - स्लॉटरहाउस-फाइव",
       "कल की सीमाएँ आज के संदेह हैं। - द ओल्ड मैन एंड द सी",
       "कृतज्ञता से ही जीवन समृद्ध बनता है। - द ब्रदर्स करमाज़ोव",
       "किसी पर भरोसा करने का सबसे अच्छा तरीका है — उस पर भरोसा करना। - द सन ऑल्सो राइज",
       "कोई चीज़ अच्छी या बुरी नहीं होती, सोच उसे वैसा बना देती है। - हैमलेट",
       "हम वही हैं जो हम विश्वास करते हैं कि हम हैं। - डॉन क्विक्सोट",
       "क्या मैं ब्रह्मांड को विचलित करने की हिम्मत करता हूँ? - द लव सांग ऑफ जे. अल्फ्रेड प्रुफ्रोक",
       "जीवन का उद्देश्य प्रकृति के साथ सामंजस्य में रहना है। - ज़ेनो ऑफ सिटियम",
       "अतीत एक भूत है, भविष्य एक सपना, और हमारे पास केवल वर्तमान है। - द नेम ऑफ द विंड",
       "जो कुछ तुम सोच सकते हो, वह वास्तविक है। - डोरियन ग्रे की तस्वीर",
       "जब तक मुझे डर नहीं लगा कि मैं इसे खो दूँगा, तब तक मैंने पढ़ने से प्रेम नहीं किया। - एक परिंदा मारना",
       "मनुष्य अपने विचारों का परिणाम है; जैसा वह सोचता है, वैसा ही बनता है। - गांधी",
       "आखिरकार, कल एक और दिन है। - गॉन विद द विंड",
       "कुछ भी असंभव नहीं, यह शब्द खुद कहता है — 'मैं संभव हूँ!' - ब्रेकफास्ट एट टिफ़नीज़",
       "हम सभी अंत में कहानियाँ ही हैं, बस एक अच्छी कहानी बनाना। - डॉक्टर हू",
       "हर चीज़ में सुंदरता होती है, बस हर कोई उसे नहीं देख पाता। - द एनालेक्ट्स",
       "आगे आने वाली चीज़ें उन चीज़ों से कहीं बेहतर हैं जो हम पीछे छोड़ देते हैं। - द लास्ट बैटल",
       "अगर बारिश न होती, तो इंद्रधनुष भी न होता। - द विज़र्ड ऑफ ऑज़",
       "एक दिन मैं सही शब्द ढूँढ लूँगा, और वे सरल होंगे। - बिग सुर",
       "घर सबसे प्यारा शब्द है। - लिटिल हाउस ऑन द प्रेयरी",
       "प्रकाश सोचता है कि वह सबसे तेज़ है, पर वह गलत है। - गुड ओमेन्स",
       "जितना अधिक तुम पढ़ोगे, उतना अधिक ज्ञान प्राप्त होगा। - डॉ. सीउस",
       "एक सपना हजार वास्तविकताओं से अधिक शक्तिशाली है। - अंगूठे के छल्ले की अंगूठी",
       "शुरुआत हमेशा आज से होती है। - मैरी शेली",
       "कुछ भी काव्यात्मक रूप से समाप्त नहीं होता। यह समाप्त होता है और हम उसे कविता में बदल देते हैं। - द सन एंड हर फ्लावर्स",
       "सभी अंत भी नए प्रारंभ हैं। बस हमें उस समय पता नहीं होता। - द फाइव पीपल यू मीट इन हेवन",
       "आशा नए वर्ष के द्वार पर मुस्कुराती है। - अल्फ्रेड लॉर्ड टेनिसन",
       "सिर्फ तब हम वास्तव में जान पाते हैं जब हम सारी पढ़ाई भूल जाते हैं। - वाल्डन",
       "कुछ किताबें हमें स्वतंत्र छोड़ती हैं और कुछ किताबें हमें स्वतंत्र बनाती हैं। - राल्फ वाल्डो इमर्सन",
       "दुनिया तुम्हारे सामने है, और तुम्हें इसे वैसे ही नहीं लेना या छोड़ना है जैसा तुम आए थे। - जेम्स बाल्डविन",
       "जादू हमेशा विवरण में होता है। - द गॉड ऑफ स्मॉल थिंग्स",
       "कितनी अद्भुत बात है कि किसी को भी दुनिया सुधारने के लिए एक पल भी इंतज़ार नहीं करना पड़ता। - द डायरी ऑफ़ ऐनी फ्रैंक",
       "कुछ भी पीछे नहीं, सब कुछ सामने है, जैसा कि सड़क पर हमेशा होता है। - ऑन द रोड",
       "जीवन या तो साहसिक है या कुछ भी नहीं। - द ओपन डोर",
       "दूर जाकर और वापस आकर एक तरह की जादुई अनुभूति होती है। - द सीक्रेट गार्डन",
       "एक बच्चा, एक शिक्षक, एक किताब, एक कलम दुनिया बदल सकती है। - आई एम मलाला",
       "भविष्य उनका है जो अपने सपनों की सुंदरता पर विश्वास करते हैं। - ऐन ऑफ ग्रीन गेबल्स",
       "परियों की कहानियाँ सच से अधिक हैं: केवल इसलिए नहीं कि वे बताते हैं कि ड्रैगन मौजूद हैं, बल्कि यह भी कि ड्रैगन को हराया जा सकता है। - कोरललाइन",
]
